config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :affiliates
  root to: "affiliates#home"
  post 'products/:id', to: 'products#counter'
end

app/models/affiliate.rb
# == Schema Information
#
# Table name: affiliates
#
#  id         :integer          not null, primary key
#  name       :string
#  category   :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Affiliate < ApplicationRecord
  def self.query
    @Tiendas = Affiliate.all
    @response = []
    @Tiendas.each do |tienda|
      @url = RestClient.get(tienda.url)
      @response << JSON.parse(@url.body)
      @mamalo = []
    end
    @response.each do |array|
      array.each do |json|
        @mamalo << json
      end
    end
    @mamalo
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  store      :string
#  name       :string
#  descripton :string
#  price      :integer
#  quantity   :integer
#  category   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord

  has_attached_file :image , styles: {large: "50x50>" , medium:  "180x150" , thumb:  "25x25>" }, default_url:  "/images/missing.png" 
  validates_attachment_content_type :image , content_type:  /\Aimage\/.*\Z/
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
  # before_action :find_affiliate, only: [:create, :new, :update, :show, :destroy, :edit]
  skip_before_action :verify_authenticity_token
    REALM = "adalpada"
  ADMIN={"admin"=>"admin"}
  before_action :find_affiliate, only: [:update, :show, :destroy,:edit] 
  before_action only: [:create, :destroy, :new, :update, :edit]do
    authenticate_or_request_with_http_digest(REALM) do |admin|
      ADMIN["admin"]
    end
  end 
  def index
    @affiliate = Affiliate.all
  end

  def show 
  end

  def home  
    @affiliate = Affiliate.query
    render layout: "hpage"
    # render json: @affiliate
  end

  def new
    @affiliate = Affiliate.new
  end

  def create
    @affiliate = Affiliate.new(affiliate_params)
    if @affiliate.save
      redirect_to affiliates_path
    else
      render new, notice: 'no se pudo enviar el fomulario'
    end
  end
  
  def update
  # @product =  Product.find(params[:id])
   #@product.quantity = @product.quantity -1
   #@product.save

   #render json: @product
      
  end

  def destroy
    @affiliate.destroy
    respond_to do |format|
      format.html { redirect_to affiliates_path, notice: 'Affiliate fue eliminado con exito' }
      # format.json { head :no_content }
    end
  end
private

  def affiliate_params
    params.require(:affiliate).permit(:name,:category, :url)
  end
  def find_affiliate
    @affiliate = Affiliate.find_by(id: params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :find_product, only: [:create, :new, :update, :show, :destroy,:edit]
  skip_before_action :verify_authenticity_token
   REALM = "adalpada"
  ADMIN = {"admin"=>"admin"}
  before_action :find_product, only: [:update, :show, :destroy,:edit, :counter] 
  before_action only: [:create, :destroy, :new, :update, :edit]do
    authenticate_or_request_with_http_digest(REALM) do |admin|
      ADMIN["admin"]
    end
  end 

    def index
    @product = Product.all

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      puts "hola"
      redirect_to products_path
    else
      render new, notice: 'no se pudo enviar el fomulario'
    end
  end

  def show
    @product
  end

    def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'El producto fue elminado con exito.' }
      # format.json { head :no_content }
    end
  end

  def edit
    @product
  end

    def counter
    @product = Product.find_by(id: params[:id])
    a = @product.quantity-1
    @product.quantity = a
    @product.save
    render json: @product.quantity

    #ahhhhhhhhhhhhhhh
  end

  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:store, :name, :description, :price, :quantity, :category, :image)
    # falta inmagen
  end

  def find_product
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/affiliates/home.html.haml
<<<<<<< HEAD
%h1{:style => "position: fixed;left: 43%;"}  Product List}
/*.form1*/
%table{:border => 3, :style => "position: absolute;left: 50%;top: 50%;-webkit-transform: translate(-50%, -50%);"}
  %thead
    %tr
      %th Image 
      %th Store
      %th Name
      %th Description
      %th Price
      %th Quantity
      %th Category
  %tbody 
    - @affiliate.each do |object|
      %tr
        %td= image_tag object["image"]
        %td= object["store"]
        %td= object["name"]
        %td= object["description"]
        %td= object["price"]
        %td= object["quantity"]
        %td= object["category"]
        %td= link_to 'counter',"/products/#{object['id']}", method: :post 
        -# %td= link_to 'Show', object
        
=======
%h1.small_top.absolute.large_left Product List
.container
  - @affiliate.each do |object|
    .card  
      - if object["image"].nil?
        =image_tag "missing.png"
      -else
        = image_tag object["image"]
      %div.padding-mini.Border-Botton-dotted
        %p.medium
          = object["name"]
      .description.padding-mini.Border-Botton
        = object["description"]
      %div.padding-mini.Border-Botton  
        %p
          = object["store"]
      .inline-blok.padding-mini.Border-Botton 
        precio:
        = object["price"]
        Bsf.
      .inline-blok.padding-mini.Border-Botton 
        cantidad:
        = object["quantity"]
      %div.padding-mini.Border-Botton
        = object["category"]
      .buttom comprar
>>>>>>> b1b49bf08d4d0276eb795c92b79e20dc893133ac

app/views/affiliates/index.html.haml
%h1.small_top.absolute.large_left Affilaite List

%table
  %thead
    %tr
      %th Name
      %th Category
      %th Url

    - @affiliate.each do |object|
      %tr
        %td= object.name
        %td= object.category
        %td= object.url
        %td= link_to 'Destroy', object, method: :delete, data: { confirm: 'Are you sure?' }

%br/

app/views/affiliates/new.html.haml
.afili-form.form1
  = form_with model: @affiliate, local: true do |form|

    .field
      = form.text_field :name, placeholder: "Nombre"
    .field
      = form.text_field :category,placeholder:"Categoria"
    .field
      = form.text_field :url, placeholder:"URL"
    .field
      = form.submit

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Market
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'navs/nav'
    = yield

app/views/layouts/hpage.html.haml
!!!5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Market
    = csrf_meta_tags
    = stylesheet_link_tag    'hpage', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'navs/navroot'
    = yield

app/views/navs/_nav.html.haml
%ul
  %li
    = link_to 'Afiliados', affiliates_path
  %li
    = link_to 'Afiliar', new_affiliate_path
  %li
    = link_to 'Productos', products_path
  %li
    = link_to 'Nuevo Producto', new_product_path 
  %li
    = link_to 'Tienda', root_path

app/views/navs/_navroot.html.haml
%ul
  %li
    = link_to 'login', products_path
 

app/views/products/_nav.html.haml
%ul
  %li
    = link_to 'Productos', products_path
  %li
    = link_to 'Afiliados', affiliates_path
  %li
    = link_to 'Producto Nuevo', new_product_path 

app/views/products/edit.html.haml
.form1
  = form_with model: @product, local: true do |form|
    .field
      = form.label :store
      = form.text_field :store
    .field
      = form.label :name
      = form.text_field :name
    .field
      = form.label :description
      = form.text_area :description
    .field
      = form.label :price
      = form.number_field :price
    .field
      = form.label :quantity
      = form.number_field :quantity
    .field
      = form.label :category
      = form.text_field :category 
    .field
      = form.submit

-#   GUSTAVO PA

app/views/products/index.html.haml
%h1.small_top.absolute.large_left Product List
.content-table
  %table{:border => 1}
    %thead
      %tr
        %th Image 
        %th Store
        %th Name
        %th Description
        %th Price
        %th Quantity
        %th Category
      
      - @product.each do |object|
        
        %tr
          %td= image_tag object.image(:medium)
          %td= object.store
          %td= object.name
          %td= object.description
          %td= object.price
          %td= object.quantity
          %td= object.category
          %td= link_to 'Show', object
          %td= link_to 'Edit', edit_product_path(object)
          %td= link_to 'Destroy', object, method: :delete, data: { confirm: 'Are you sure?' }

%br/

app/views/products/new.html.haml
.form1
  = form_with model: @product, local: true do |form|

    .field
      = form.text_field :store,placeholder:"Store"
  
    .field
      = form.text_field :name,placeholder:"Nombre"

    .field
      = form.text_area :description,placeholder:"Descripcion.."
   
    .field
      = form.number_field :price,placeholder:"Precio"
    
    .field
      = form.number_field :quantity,placeholder:"Cantidad"
  
    .field
      = form.text_field :category ,placeholder:"Categoria"
    .field
      = form.file_field :image,placeholder:"Hola"
    .field
      = form.submit

.fondo

app/views/products/show.html.haml
%ul
  %li
    Store:
    #{@product.store} 
  %li
    Name:
    #{@product.name} 
  %li
    Description:
    #{@product.description} 
  %li
    Price:
    #{@product.price} 
  %li
    Quantity:
    #{@product.quantity} 
  %li
    Category
    #{@product.category} 